pipeline {
    agent { 
        node {
            label 'docker-agent-dotnet'
            }
      }
    triggers {
        pollSCM 'H/5 * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                echo "doing build operations.."
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing...."
                sh '''
                echo "doing test operations.."
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver......'
                sh '''
                echo "doing delivery operations.."
                '''
            }
        }
    }
}